version: '3.8'

services:
  godot-ci:
    image: barichello/godot-ci:4.3
    container_name: godot-ci
    restart: unless-stopped
    volumes:
      - ./exported:/exported
    environment:
      GODOT_VERSION: "4.3"
      EXPORT_NAME: "io"
      PROJECT_PATH: "./"
    working_dir: /project
    platform: linux/arm64  # Specify the platform

    command: >
      sh -c "if [ -d 'io' ]; then 
        rm -rf io; 
      fi; 
      git clone https://github.com/lanmower/io.git; 
      cd io && 
      godot --headless"
