version: '3.8'

services:
  godot-ci:
    build:
      context: .  # Change this as needed to point to your Dockerfile directory
      dockerfile: Dockerfile  # Point to the Dockerfile
    container_name: godot-ci
    restart: unless-stopped
    environment:
      GODOT_VERSION: "4.3"
      EXPORT_NAME: "io"
      PROJECT_PATH: "./"
    working_dir: /project
    platform: linux/arm64

    command: >
      godot --headless --export-release Linux/ARM64 export/io.arm64 &&
      cd export
      ./io.arm64 --headless
